version: '3'
services:
  springboot:
    image: yeonsusim/springboot_app:latest
    container_name: springboot
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/jnu-sf?serverTimezone=Asia/Seoul
    ports:
      - '8081:8080'
    restart: always
    depends_on:
      - db
  db:
    image: yeonsusim/mysql_app:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: jnu-sf
      MYSQL_USER: jnu-sf-engineering
      MYSQL_PASSWORD: jnu-sf-engineering
      MYSQL_ROOT_PASSWORD: jnu-sf-engineering
    ports:
      - '3306:3306'
    volumes:
      - 'mysql-data:/var/lib/mysql'
      - './schema.sql:/docker-entrypoint-initdb.d/schema.sql'
volumes:
  mysql-data:
