USE jnu-sf;

CREATE TABLE USER (
    USER_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    PRIMARY KEY (USER_ID)
) ENGINE=InnoDB;

CREATE TABLE PROJECT (
    PROJECT_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
    USER_ID BIGINT(20) NOT NULL,
    PROJECT_NAME VARCHAR(255) NOT NULL,
    SPRINT_COUNT TINYINT NULL,
    MANAGER VARCHAR(255) NOT NULL,
    PRIMARY KEY (PROJECT_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID)
) ENGINE=InnoDB;

CREATE TABLE SUMMARY (
    SUMMARY_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
    PROJECT_ID BIGINT(20) NOT NULL,
    SUMMARY_CONTENT VARCHAR(255) NOT NULL,
    LAST_UPDATED DATETIME(6) NOT NULL,
    PRIMARY KEY (SUMMARY_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID)
) ENGINE=InnoDB;

CREATE TABLE SPRINT (
    SPRINT_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
    PROJECT_ID BIGINT(20) NOT NULL,
    SPRINT_NAME VARCHAR(255) NOT NULL,
    START_DATE DATETIME(6) NOT NULL,
    END_DATE DATETIME(6) NOT NULL,
    PRIMARY KEY (SPRINT_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (PROJECT_ID)
) ENGINE=InnoDB;

CREATE TABLE CARD (
    CARD_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
    SPRINT_ID BIGINT(20) NOT NULL,
    CARD_CONTENT VARCHAR(255) NOT NULL,
    CARD_PARTICIPANTS VARCHAR(255) NOT NULL,
    CARD_STATUS TINYINT NOT NULL,
    PRIMARY KEY (CARD_ID),
    FOREIGN KEY (SPRINT_ID) REFERENCES SPRINT (SPRINT_ID)
) ENGINE=InnoDB;

CREATE TABLE RETROSPECT (
    RETRO_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
    SPRINT_ID BIGINT(20) NOT NULL,
    SUMMARY VARCHAR(255) NOT NULL,
    PRIMARY KEY (RETRO_ID),
    FOREIGN KEY (SPRINT_ID) REFERENCES SPRINT (SPRINT_ID)
) ENGINE=InnoDB;

CREATE TABLE KPT (
    RETRO_ID BIGINT(20) NOT NULL,
    KEEP VARCHAR(255) NULL,
    PROBLEM VARCHAR(255) NULL,
    TRY VARCHAR(255) NULL,
    PRIMARY KEY (RETRO_ID),
    FOREIGN KEY (RETRO_ID) REFERENCES RETROSPECT (RETRO_ID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE FOUR_LS (
    RETRO_ID BIGINT(20) NOT NULL,
    LIKED VARCHAR(255) NULL,
    LEARNED VARCHAR(255) NULL,
    LACKED VARCHAR(255) NULL,
    LOGGED_FOR VARCHAR(255) NULL,
    PRIMARY KEY (RETRO_ID),
    FOREIGN KEY (RETRO_ID) REFERENCES RETROSPECT (RETRO_ID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE CSS (
    RETRO_ID BIGINT(20) NOT NULL,
    CSS_CONTINUE VARCHAR(255) NULL,
    CSS_STOP VARCHAR(255) NULL,
    CSS_START VARCHAR(255) NULL,
    PRIMARY KEY (RETRO_ID),
    FOREIGN KEY (RETRO_ID) REFERENCES RETROSPECT (RETRO_ID) ON DELETE CASCADE
) ENGINE=InnoDB;